### ISSUE TITLE
SystemJS support

### ISSUE THREAD

**Issue by maddy2get** [cschroeter/ng2-pickadate#11]
Hi there, great module but unfortunately does not work with SystemJS module loader. Would it be possible to support for SystemJS support as many people are using systemJS and they don't want to migrate to webpack just yet.

Thanks heaps ;-)

**Comment by sholzmayer** [comment]
Hi,
I'm sorry, but in an earlier version we decided against SystemJS and chose webpack. So we wouldn't change this in the near future for ng2-pickadate. 

Nevertheless thanks for your feedback!
