### ISSUE TITLE
Provide Jquery to be used in my application

### ISSUE THREAD

**Issue by celsoagra** [cschroeter/ng2-pickadate#4]
I'm new on angular2, and I don't have any idea about this.
Could somebody help me, please?

I have some problems to provide the jquery in my application.
In the [installation guide](https://github.com/cschroeter/ng2-pickadate/blob/master/docs/angular-cli.md), there is a step to add the jquery if is it not defined.

My application says jquery is not found, so I'd like to know where I should provide this line of code in my application:
`window['$'] = require('jquery');`

**Comment by sholzmayer** [comment]
Did you install _jQuery_ using npm? 
You should include this part of code just before importing the `PickadateModule` in the `NgModule`.

**Comment by sholzmayer** [comment]
I think you also should use the full path to the jquery-bundle using `window['$'] = require('jquery/dist/jquery');`. 
This was documented wrong. Just added this in the last commit.

**Comment by celsoagra** [comment]
Thanks for your answer.
I'll try to do that using the full path, and. I'll give you a feedback soon.

Thanks
