### ISSUE TITLE
Model / Display values should be independent

### ISSUE THREAD

**Issue by rosslavery** [cschroeter/ng2-pickadate#7]
Currently, when I pass in an integer as my model `1477540800000`, along with a format `mmm. d, yyyy`, I would expect it to retain the format of my model while _presenting_ the value according to the format.

Instead, it re-formats my model value to match the `format` that I passed in. The same thing applies when selecting a subsequent date from the datepicker popup. It sets the model according to the format.

My understanding of the format input is that it should be for presentation only, and should not affect the format that the model is stored in. That seems to be the intention of the pickadate format option according to: http://amsul.ca/pickadate.js/api/#method-set-select

**Comment by sholzmayer** [comment]
...as you can see on the ng2-pickadate demo page [Demo Page](https://cschroeter.github.io/ng2-pickadate/).
