### ISSUE TITLE
Feature: AoT compatibility

### ISSUE THREAD

**Issue by thbt** [cschroeter/ng2-pickadate#8]
First of all, thank you for your work !

This library doesn't work when using AoT, would it be possible to make it compatible with Ahead-of-Time compilation ?

**Comment by sholzmayer** [comment]
Thank you for your feedback.

I don't know exactly if it's possible using AoT with the jQuery lib. 

If you're interested in developing it, I would accept a pull request for this issue.

**Comment by wbhob** [comment]
It is possible and we all desperately need this. https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad
