### ISSUE TITLE
Install with SystemJS?

### ISSUE THREAD

**Issue by alfupe** [cschroeter/ng2-pickadate#9]
Hi there,

Thanks for your work!

I'm using SystemJS. I tried to install in systemjs.config.js like that

```
map: {
            ...
            'ng2-pickadate': 'npm:ng2-pickadate',
            ...
        },
        packages: {
            ...
            'ng2-pickadate': {
                main: '/lib/ng2Pickadate.module.js',
                defaultExtension: 'js'
            }
            ...
        }
```

And after that my console is throwing tons of Not Found errors like those:
```
GET http://localhost:3000/@angular/material 404 (Not Found)
GET http://localhost:3000/lodash 404 (Not Found)
GET http://localhost:3000/moment 404 (Not Found)
GET http://localhost:3000/jquery/dist/jquery 404 (Not Found)
GET http://localhost:3000/pickadate/lib/translations/de_DE 404 (Not Found)
GET http://localhost:3000/pickadate/lib/translations/es_ES 404 (Not Found)
GET http://localhost:3000/pickadate/lib/translations/fr_FR 404 (Not Found)
GET http://localhost:3000/jquery 404 (Not Found)
GET http://localhost:3000/node_modules/ng2-pickadate/jquery.js 404 (Not Found)
```

Is it possible to run this wrapper with SystemJS or is time to move to another alternative? 

Thanks a lot

**Comment by sholzmayer** [comment]
Using angular-cli I would suggest webpack to build your application. This is also the way how the angular team does (https://angular.io/docs/ts/latest/guide/webpack.html)

In an earlier version of ng2-pickadate we replaced the systemjs-loader by webpack. It is not longer supported from us.

**Comment by alfupe** [comment]
We started working with angular-cli but we got bored with the problems that came up again and again. We will wait for a more solid phase. Still too much beta... Thanks anyway ;-)
